FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    clang \
    llvm \
    lld \
    libclang-dev \
    libgtk-3-dev \
    libxcb-randr0-dev \
    libxdo-dev \
    libxfixes-dev \
    libxcb-shape0-dev \
    libxcb-xfixes0-dev \
    libasound2-dev \
    libpulse-dev \
    libva-dev \
    libvdpau-dev \
    patchelf \
    pkg-config \
    cmake \
    ninja-build \
    nasm \
    yasm \
    zip \
    unzip \
    curl \
    git \
    python3 \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Baixar e colocar a libsciter-gtk.so no container
RUN mkdir -p /opt/sciter && \
    wget https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.lnx/x64/libsciter-gtk.so -O /usr/lib/libsciter-gtk.so && \
    chmod 755 /usr/lib/libsciter-gtk.so

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustup target add i686-unknown-linux-gnu && \
    cargo install cargo-bundle

WORKDIR /home/user/rustdesk
