name: Sunev Windows 64-bits Release Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  # 1. GERAR PONTE RUST-FLUTTER
  generate-bridge:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: '1.85.0'
          components: rustfmt

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Install codegen
        run: |
          cargo install flutter_rust_bridge_codegen --version 1.80.1 --features "uuid"
          cd flutter && flutter pub get

      - name: Run bridge
        run: |
          ~/.cargo/bin/flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart --c-output ./flutter/macos/Runner/bridge_generated.h --skip-deps-check
          cp ./flutter/macos/Runner/bridge_generated.h ./flutter/ios/Runner/bridge_generated.h

      - name: Upload Bridge Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridge-artifact
          path: |
            ./src/bridge_generated.rs
            ./src/bridge_generated.io.rs
            ./flutter/lib/generated_bridge.dart
            ./flutter/lib/generated_bridge.freezed.dart

  # 2. WINDOWS 64-BITS PORTABLE
  build-windows-64:
    needs: [generate-bridge]
    name: Windows 64bits
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Bridge
        uses: actions/download-artifact@v4
        with:
          name: bridge-artifact
          path: ./

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "15.0.6"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.75"
          targets: x86_64-pc-windows-msvc
          components: rustfmt

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      - name: Setup ALL VCPKG Dependencies
        shell: pwsh
        run: |
          vcpkg install --classic opus:x64-windows-static libyuv:x64-windows-static libvpx:x64-windows-static aom:x64-windows-static ffmpeg:x64-windows-static pkgconf:x64-windows-static

      - name: Build RustDesk & Zip Windows Package
        shell: pwsh
        env:
          VCPKG_ROOT: "C:/vcpkg"
          VCPKG_DEFAULT_TRIPLET: "x64-windows-static"
        run: |
          python3 .\build.py --portable --flutter --skip-portable-pack
          mkdir -p dist_app
          cp -Recurse ./flutter/build/windows/x64/runner/Release/* dist_app/
          if (Test-Path "dist_app/rustdesk.exe") {
              Rename-Item -Path "dist_app/rustdesk.exe" -NewName "Sunev.exe"
          }
          Compress-Archive -Path dist_app/* -DestinationPath ./Sunev-Windows-64bits.zip

      - name: Publish Windows 64 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v1.0.0-build"
          files: Sunev-Windows-64bits.zip
# Clean Yaml formatting for Windows 64-bit build
